apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idptest001
  description: STACKIT SKE Cluster (k8s 1.35.6) provisioned via stackit-compute-operator.
  annotations:
    backstage.io/kubernetes-id: idptest001
    backstage.io/kubernetes-namespace: default
  tags:
    - stackit
    - ske
    - kubernetes
    - dev
spec:
  type: stackit-ske-cluster
  lifecycle: dev
  owner: user:default/bart.van.benthem
  system: stackit-compute
  dependsOn: []
